# -*- coding: utf-8 -*-
"""런타임 한국어 전환 모듈 (자동 생성 2026-05-21).

위젯 소스의 UI 문자열은 _t("원문") 로 감싸여 있다.
- 한국어 세션: _KO 사전에서 번역 반환
- 그 외 언어(영어/슬로베니아어): 원문 그대로 반환
→ 영어 세션에는 한국어가 절대 노출되지 않음 (언어 분리 보장).
"""
try:
    from AnyQt.QtCore import QSettings
except Exception:  # pragma: no cover
    QSettings = None


def _current_lang():
    if QSettings is None:
        return "English"
    try:
        s = QSettings(QSettings.IniFormat, QSettings.UserScope,
                      "biolab.si", "Orange")
        return s.value("application/language", "English")
    except Exception:
        return "English"


def _t(s):
    """한국어 세션이면 번역, 아니면 원문."""
    if _current_lang() == "Korean":
        return _KO.get(s, s)
    return s


_KO = {
    "   English": "   영어",
    " (forecast)": " (예측)",
    " works with local models.": " 로컬 모델에서 작동합니다.",
    "% unique words": "고유 단어 비율(%)",
    "&Apply": "적용(&A)",
    "(no title)": "(제목 없음)",
    "(none)": "(없음)",
    "Absolute:": "절대값:",
    "Add document": "문서 추가",
    "Add plot": "플롯 추가",
    "Aggregate time periods": "기간 집계",
    "Aggregate was replaced with Moving Transform; ": "Aggregate 위젯은 Moving Transform 으로 대체되었습니다; ",
    "Aggregation Type": "집계 유형",
    "All Topics": "모든 주제",
    "All files (*)": "모든 파일 (*)",
    "All readable files ({});;": "읽을 수 있는 모든 파일 ({});;",
    "Apply": "적용",
    "At least one text feature must be used.": "최소 한 개의 텍스트 특성을 사용해야 합니다.",
    "Auto commit is on": "자동 커밋 켜짐",
    "Auto send is on": "자동 전송 켜짐",
    "Average term length": "평균 용어 길이",
    "Average word length": "평균 단어 길이",
    "Bigrams": "바이그램",
    "Block width": "블록 너비",
    "Block width is too large": "블록 너비가 너무 큽니다",
    "Block width:": "블록 너비:",
    "Browse": "찾아보기",
    "Browse Documentation Corpora": "문서 말뭉치 찾아보기",
    "Calculating...": "계산 중...",
    "Can't read file ({})": "파일을 읽을 수 없습니다 ({})",
    "Capital letter count": "대문자 수",
    "Character count": "문자 수",
    "Chi Square": "카이제곱",
    "Cloud preferences": "클라우드 환경설정",
    "Collocation": "연어",
    "Collocation Scores": "연어 점수",
    "Color words": "단어 색상",
    "Commit": "커밋",
    "Compute for": "계산 대상",
    "Compute partial auto-correlation": "부분 자기상관 계산",
    "Conc. {}": "용례 {}",
    "Concordances": "용례 색인",
    "Consecutive blocks": "연속 블록",
    "Consonant count": "자음 수",
    "Contains": "포함",
    "Contains {text}": "{text} 포함",
    "Corpus File": "말뭉치 파일",
    "Corpus Settings": "말뭉치 설정",
    "Corpus doesn't have any textual features.": "말뭉치에 텍스트 특성이 없습니다.",
    "Custom Dictionaries": "사용자 사전",
    "Custom dictionary": "사용자 사전",
    "Data": "데이터",
    "Dataset": "데이터셋",
    "Decomposition model:": "분해 모델:",
    "Discard original data": "원본 데이터 버리기",
    "Display features": "특성 표시",
    "Document": "문서",
    "Document Count": "문서 수",
    "Document text": "문서 텍스트",
    "Document title": "문서 제목",
    "Documents": "문서",
    "Ends with": "다음으로 끝남",
    "Ends with {postfix}": "{postfix}(으)로 끝남",
    "Feature": "특성",
    "Features": "특성",
    "File": "파일",
    "File not found.": "파일을 찾을 수 없습니다.",
    "Filter ...": "필터 ...",
    "Filtering": "필터링",
    "Filtering has been ignored due to ": "다음 이유로 필터링이 무시되었습니다: ",
    "First level concentration (γ)": "1단계 집중도 (γ)",
    "Forecast": "예측",
    "Frequency": "빈도",
    "Ignored Text Features": "무시된 텍스트 특성",
    "Ignored text features": "무시된 텍스트 특성",
    "Include leading instances": "선행 인스턴스 포함",
    "Info": "정보",
    "Input signal Topic takes priority over Corpus": "입력 신호 Topic 이 Corpus 보다 우선합니다",
    "Instance count": "인스턴스 수",
    "Invalid file encoding. Please save the ": "잘못된 파일 인코딩입니다. 파일을 ",
    "Invalid regular expression.": "잘못된 정규식입니다.",
    "Keep first instance": "첫 인스턴스 유지",
    "Keep last instance": "마지막 인스턴스 유지",
    "Keep middle instance": "중간 인스턴스 유지",
    "Keep original data": "원본 데이터 유지",
    "LIX index": "LIX 지수",
    "Language": "언어",
    "Language:": "언어:",
    "Latent Dirichlet Allocation": "잠재 디리클레 할당 (LDA)",
    "Learning rate (κ)": "학습률 (κ)",
    "Less topics found than requested.": "요청한 것보다 적은 주제가 발견되었습니다.",
    "LiLaH Sentiment": "LiLaH 감성",
    "Likelihood ratio": "우도비",
    "Lilah sentiment": "LiLaH 감성",
    "Loading": "불러오는 중",
    "Log perplexity: %(perplexity)s": "로그 혼잡도: %(perplexity)s",
    "Logarithmic axis": "로그 축",
    "Matches": "일치",
    "Matches: %(n_matches)s": "일치: %(n_matches)s",
    "Matching": "일치",
    "Matching Docs": "일치 문서",
    "Matching documents": "일치 문서",
    "Matching documents: %(n_matching)s": "일치 문서: %(n_matching)s",
    "Matching: %(n_matching)s": "일치: %(n_matching)s",
    "Method": "방법",
    "Multilingual ": "다국어 ",
    "Multilingual Sentiment": "다국어 감성",
    "Multiple query words on input. ": "입력에 여러 질의어가 있습니다. ",
    "N-gram count": "N-그램 수",
    "N-grams": "N-그램",
    "N-grams Range": "N-그램 범위",
    "Negative:": "부정:",
    "No (applicable) aggregations are selected": "적용 가능한 집계가 선택되지 않았습니다",
    "No UDPipe model is selected.": "UDPipe 모델이 선택되지 않았습니다.",
    "No dictionaries loaded.": "불러온 사전이 없습니다.",
    "No features included in search.": "검색에 포함된 특성이 없습니다.",
    "No features selected for display.": "표시할 특성이 선택되지 않았습니다.",
    "No internet connection. ": "인터넷 연결이 없습니다. ",
    "No internet connection. UDPipe": "인터넷 연결이 없습니다. UDPipe",
    "No tokens on the output.": "출력에 토큰이 없습니다.",
    "Normalization": "정규화",
    "Normalization, Filtering, n-grams and ": "정규화, 필터링, N-그램 및 ",
    "Number of topics": "주제 수",
    "Number of words:": "단어 수:",
    "Only one dictionary loaded.": "사전이 하나만 불러와졌습니다.",
    "Only the first one is considered!": "첫 번째 것만 적용됩니다!",
    "Open Orange Document Corpus": "Orange 문서 말뭉치 열기",
    "Open...": "열기...",
    "Options": "옵션",
    "Original data": "원본 데이터",
    "Other Docs": "기타 문서",
    "Other features": "기타 특성",
    "Output": "출력",
    "Output data will contain only aggregates.": "출력 데이터는 집계값만 포함합니다.",
    "POS Tagger": "품사 태거",
    "POS Tagger.": "품사 태거.",
    "POS tag": "품사 태그",
    "POS tags {pos_tags}": "품사 태그 {pos_tags}",
    "Pattern": "패턴",
    "Pattern:": "패턴:",
    "Per cent unique terms": "고유 용어 비율(%)",
    "Period": "주기",
    "Phi Square": "파이제곱",
    "Plot 95% significance interval": "95% 유의 구간 표시",
    "Pointwise Mutual Information": "점별 상호정보량 (PMI)",
    "Positive:": "긍정:",
    "Preview": "미리보기",
    "Punctuation count": "구두점 수",
    "Query": "질의",
    "Query Word": "질의어",
    "Query:": "질의:",
    "Range:": "범위:",
    "Raw Frequency": "원시 빈도",
    "RegExp Filter:": "정규식 필터:",
    "Regex": "정규식",
    "Regex {expression}": "정규식 {expression}",
    "Relative:": "상대값:",
    "Reload": "다시 불러오기",
    "Restore Original Order": "원래 순서로 복원",
    "Score": "점수",
    "Scores": "점수",
    "Scoring Method": "점수화 방법",
    "Search features": "특성 검색",
    "Season period:": "계절 주기:",
    "Second level concentration (α)": "2단계 집중도 (α)",
    "Second level truncation level (Κ)": "2단계 절단 수준 (Κ)",
    "Selected Documents": "선택된 문서",
    "Selected Topic": "선택된 주제",
    "Selected Words": "선택된 단어",
    "Send data": "데이터 전송",
    "Sentiment cannot be computed since you are offline and the ": "오프라인 상태이고 다음이 없어 감성을 계산할 수 없습니다: ",
    "Settings": "설정",
    "Show Tokens && Tags": "토큰 및 태그 표시",
    "Show only numeric variables": "수치형 변수만 표시",
    "Show rows in the original order": "행을 원래 순서로 표시",
    "Showing bag of words weights.": "단어 가방 가중치를 표시 중입니다.",
    "Sliding Window": "슬라이딩 윈도우",
    "Sliding window": "슬라이딩 윈도우",
    "Slow down parameter (τ)": "감속 매개변수 (τ)",
    "Some aggregations are applicable ": "일부 집계는 다음에만 적용 가능합니다 ",
    "Starts with": "다음으로 시작함",
    "Starts with {prefix}": "{prefix}(으)로 시작함",
    "Table": "테이블",
    "Target": "대상",
    "Text files (*.txt)": "텍스트 파일 (*.txt)",
    "The expected length of full cycle. E.g., if you have ": "전체 주기의 예상 길이. 예: ",
    "The topic Dirichlet (α)": "주제 디리클레 (α)",
    "Time series": "시계열",
    "Time series has to have at least 3 instances.": "시계열은 최소 3개의 인스턴스가 있어야 합니다.",
    "Title": "제목",
    "Title variable": "제목 변수",
    "Tokenization": "토큰화",
    "Tokenization has been ignored due to ": "다음 이유로 토큰화가 무시되었습니다: ",
    "Tokenization should be placed before ": "토큰화는 다음 앞에 위치해야 합니다: ",
    "Tokens": "토큰",
    "Tokens: %(n_tokens)s": "토큰: %(n_tokens)s",
    "Top level truncation level (Τ)": "최상위 절단 수준 (Τ)",
    "Topic": "주제",
    "Topic coherence: %(coherence)s": "주제 일관성: %(coherence)s",
    "Topic evaluation": "주제 평가",
    "Topic keywords": "주제 키워드",
    "Topics": "주제",
    "Transformation": "변환",
    "Transformations": "변환",
    "Trigrams": "트라이그램",
    "Type:": "유형:",
    "Types": "유형",
    "Types: %(n_types)s": "유형: %(n_types)s",
    "UDPipe model is not available.": "UDPipe 모델을 사용할 수 없습니다.",
    "UDPipe tokenizer": "UDPipe 토크나이저",
    "UDPipe tokenizer.": "UDPipe 토크나이저.",
    "Used Text Features": "사용된 텍스트 특성",
    "Used text features": "사용된 텍스트 특성",
    "Vowel count": "모음 수",
    "Weight": "가중치",
    "Window width": "윈도우 너비",
    "Window width is too large": "윈도우 너비가 너무 큽니다",
    "Window width:": "윈도우 너비:",
    "Word": "단어",
    "Word Count": "단어 수",
    "Word Counts": "단어 수",
    "Word count": "단어 수",
    "Words && weights": "단어 및 가중치",
    "Words tilt:": "단어 기울기:",
    "Wrong source {source}": "잘못된 소스 {source}",
    "Years": "연도",
    "except for the first N-1 (where N is window width).": "첫 N-1개(N은 윈도우 너비)는 제외합니다.",
    "exhibits a seasonal pattern.": "계절 패턴을 보이는.",
    "file as UTF-8 and try again.": "UTF-8로 저장한 뒤 다시 시도하세요.",
    "is not computed.": "계산되지 않습니다.",
    "manually re-set the widget": "위젯을 수동으로 다시 설정하세요",
    "required dictionary is unavailable locally.": "필요한 사전을 로컬에서 사용할 수 없습니다.",
    "year, you put in 12.": "예를 들어 12를 입력합니다.",

    # ── H 추가 (2026-05-26): text·timeseries 공통 widget UI 라벨 ──────────
    "Cancel": "취소",
    "Cancelled": "취소됨",
    "Commit": "전송",
    "Compute": "계산",
    "Compute for": "계산 대상",
    "Confidence interval": "신뢰 구간",
    "Confidence:": "신뢰도:",
    "Categorical": "범주형",
    "Count": "개수",
    "Color": "색상",
    "Color words": "색상 단어",
    "Author": "작성자",
    "Annotation": "주석",
    "Apply": "적용",
    "Bearer Token": "Bearer 토큰",
    "Bin width": "구간 너비",
    "Browse": "찾아보기",
    "Browse Documentation Corpora": "문서 코퍼스 찾아보기",
    "Centuries": "세기",
    "Character count": "글자 수",
    "Capital letter count": "대문자 수",
    "Consonant count": "자음 수",
    "Chi Square": "카이제곱",
    "Cloud preferences": "워드 클라우드 환경설정",
    "Collocation": "연어",
    "Collocation Scores": "연어 점수",
    "Concordances": "용례 색인",
    "Corpus File": "코퍼스 파일",
    "Corpus Settings": "코퍼스 설정",
    "Corpus doesn't have any textual features.": "코퍼스에 텍스트 특성이 없습니다.",
    "Correlogram": "코렐로그램",
    "Cubic interpolation": "3차 보간",
    "Aggregator": "집계기",
    "Aggregator:": "집계기:",
    "Aggregation": "집계",
    "Annotated Corpus Map": "주석 추가된 코퍼스 맵",
    "Annotates projection clusters.": "투영 클러스터에 주석을 추가합니다.",
    "Akaike's information criterion (AIC)": "아카이케 정보 기준 (AIC)",
    "Always sort NaNs last": "NaN 은 항상 마지막에 정렬",
    "Assigned time variable": "할당된 시간 변수",
    "Agent": "에이전트",
    "Allow retweets:": "리트윗 허용:",
    "All Topics": "모든 토픽",
    "Axes": "축",
    "Axis x:": "X축:",
    "Axis y:": "Y축:",
    "Calculating...": "계산 중...",
    "Categorical variables:\n": "범주형 변수:\n",
    "Change quotient": "변화 비율",
    "Contains": "다음을 포함",
    "Contains {text}": "{text} 을(를) 포함",
    "Consecutive blocks": "연속된 블록",
    "Compute partial auto-correlation": "부분 자기상관 계산",
    "ARIMA Model": "ARIMA 모델",
    "Aggregate time periods": "시간 구간 집계",
    "Aggregation Type": "집계 유형",

    # 추가 빈도 높은 단순 라벨
    "Yes": "예",
    "No": "아니오",
    "OK": "확인",
    "Close": "닫기",
    "Reset": "초기화",
    "Back": "뒤로",
    "Next": "다음",
    "Save": "저장",
    "Save As...": "다른 이름으로 저장...",
    "Open": "열기",
    "Open...": "열기...",
    "Load": "불러오기",
    "Delete": "삭제",
    "Remove": "제거",
    "Add": "추가",
    "Edit": "편집",
    "Search": "검색",
    "Filter": "필터",
    "Settings": "설정",
    "Options": "옵션",
    "Help": "도움말",
    "Name": "이름",
    "Type": "유형",
    "Value": "값",
    "Total": "전체",
    "Mean": "평균",
    "Median": "중앙값",
    "Min": "최솟값",
    "Max": "최댓값",
    "Sum": "합계",
    "Std": "표준편차",
    "Standard deviation": "표준편차",
    "Variance": "분산",
    "Frequency": "빈도",
    "Length": "길이",
    "Loading...": "로딩 중...",
    "Loading data...": "데이터 로드 중...",
    "Saving...": "저장 중...",
    "Done": "완료",
    "Done.": "완료.",
    "Ready": "준비됨",
    "Error": "오류",
    "Warning": "경고",
    "Info": "정보",
    "Status": "상태",
    "From": "시작",
    "To": "끝",
    "Start": "시작",
    "End": "끝",
    "Show": "표시",
    "Hide": "숨김",
    "Visible": "보임",
    "Hidden": "숨김",
    "All": "전체",
    "Any": "임의",
    "Other": "기타",
    "Unknown": "알 수 없음",
    "Description": "설명",
    "Title": "제목",
    "Label": "레이블",
    "Labels": "레이블",
    "Columns": "열",
    "Rows": "행",
    "Row": "행",
    "Cell": "셀",
    "Header": "헤더",
    "Footer": "푸터",
    "Today": "오늘",
    "Yesterday": "어제",
    "Tomorrow": "내일",
    "Week": "주",
    "Weeks": "주",
    "Month": "월",
    "Months": "월",
    "Year": "연도",
    "Day": "일",
    "Days": "일",
    "Hour": "시",
    "Hours": "시",
    "Minute": "분",
    "Minutes": "분",
    "Second": "초",
    "Seconds": "초",
    "Date": "날짜",
    "Time": "시간",
    "Datetime": "날짜시간",
    "Number": "숫자",
    "Text": "텍스트",
    "URL": "URL",
    "File": "파일",
    "Folder": "폴더",
    "Path": "경로",
    "Format": "형식",
    "Language": "언어",
    "Encoding": "인코딩",
    "Source": "원본",
    "Target": "대상",
    "Input": "입력",
    "Output": "출력",
    "Parameters": "매개변수",
    "Settings:": "설정:",
    "Options:": "옵션:",
    "Selection": "선택",
    "Selected": "선택됨",
    "Unselected": "선택되지 않음",
    "Active": "활성",
    "Inactive": "비활성",
    "Enabled": "활성화됨",
    "Disabled": "비활성화됨",
    "Available": "사용 가능",
    "Unavailable": "사용 불가",
    "Required": "필수",
    "Optional": "선택 사항",

    # ── H-2차 추가 (2026-05-26): 위젯 안 미커버 영문 라벨 ──────────────────
    "Mode": "모드",
    "More": "더보기",
    "Redo": "다시 실행",
    "Sort": "정렬",
    "Stop": "중지",
    "Test": "테스트",
    "Undo": "실행 취소",
    "URL:": "URL:",
    "Ward": "Ward",
    "Lemma": "표제어",
    "Model": "모델",
    "Shape": "모양",
    "Union": "합집합",
    "Words": "단어",
    "World": "세계",
    "Corpus": "코퍼스",
    "DBSCAN": "DBSCAN",
    "Delay:": "지연:",
    "Europe": "유럽",
    "Fisher": "피셔",
    "LDAvis": "LDAvis",
    "Liu Hu": "Liu Hu",
    "Manual": "수동",
    "Radial": "방사형",
    "Single": "단일",
    "Subset": "부분집합",
    "Update": "갱신",
    "Average": "평균",
    "Cluster": "클러스터",
    "Display": "표시",
    "Folder:": "폴더:",
    "Include": "포함",
    "Jaccard": "자카드",
    "Library": "라이브러리",
    "Linkage": "연결",
    "Section": "섹션",
    "Clusters": "클러스터",
    "Complete": "완전",
    "Generate": "생성",
    "Keywords": "키워드",
    "LsiModel": "LsiModel",
    "Max lag:": "최대 시차:",
    "Min. lag": "최소 시차",
    "One file": "하나의 파일",
    "OntoType": "OntoType",
    "Ontology": "온톨로지",
    "POS tags": "품사 태그",
    "Sentence": "문장",
    "SentiArt": "SentiArt",
    "Series 1": "시리즈 1",
    "Series 2": "시리즈 2",
    "Untitled": "제목없음",
    "Update: ": "갱신: ",
    "WordList": "단어 목록",
    "Adj Close": "수정 종가",
    "Distances": "거리",
    "Filter...": "필터...",
    "Gridlines": "격자선",
    "Map type:": "지도 유형:",
    "Relevance": "관련성",
    "Top words": "상위 단어",
    "Word List": "단어 목록",
    "Categories": "카테고리",
    "Duplicates": "중복",
    "FDR values": "FDR 값",
    "Line Chart": "선 차트",
    "Only input": "입력만",
    "Processing": "처리 중",
    "Similarity": "유사도",
    "Some files": "일부 파일",
    "Statistics": "통계",
    "Time Slice": "시간 슬라이스",
    "Timeseries": "시계열",
    "Word Cloud": "워드 클라우드",
    "Concordance": "용례",
    "Day of year": "연중 일",
    "Error state": "오류 상태",
    "Input Words": "입력 단어",
    "Periodogram": "주기도",
    "Remove word": "단어 제거",
    "Shown topic": "표시 토픽",
    "Spiralogram": "Spiralogram",
    "Threshold: ": "임계값: ",
    "Time Period": "시간 구간",
    "Collocations": "연어",
    "Day of month": "월중 일",
    "Document Map": "문서 지도",
    "Granger Test": "Granger 테스트",
    "Ignore input": "입력 무시",
    "Intersection": "교집합",
    "More actions": "추가 작업",
    "Redraw graph": "그래프 다시 그리기",
    "Select Words": "단어 선택",
    "Week of year": "연중 주",
    "Corpus Viewer": "코퍼스 뷰어",
    "Create Corpus": "코퍼스 생성",
    "From variable": "변수에서",
    "Listing words": "단어 목록 표시 중",
    "Loop playback": "반복 재생",
    "Ontology info": "온톨로지 정보",
    "Open Ontology": "온톨로지 열기",
    "Save Ontology": "온톨로지 저장",
    "Selected Data": "선택된 데이터",
    "Selected Docs": "선택된 문서",
    "Selected data": "선택된 데이터",
    "Top documents": "상위 문서",
    "Word presence": "단어 존재",
    "Word variable": "단어 변수",
    "Add a new word": "새 단어 추가",
    "Enriched words": "강화된 단어",
    "FDR threshold:": "FDR 임계값:",
    "Open Word List": "단어 목록 열기",
    "Save Word List": "단어 목록 저장",
    "Word variable:": "단어 변수:",
    "Cluster labels:": "클러스터 레이블:",
    "Forecast steps:": "예측 단계:",
    "Include subtree": "하위 트리 포함",
    "LineChartEditor": "선 차트 편집기",
    "Preprocess Text": "텍스트 전처리",
    "Score Documents": "문서 점수",
    "Scoring Methods": "점수 방법",
    "Semantic Viewer": "의미 뷰어",
    "Topic Modelling": "토픽 모델링",
    "Word Enrichment": "단어 강화",
    "Extract Keywords": "키워드 추출",
    "Import Documents": "문서 가져오기",
    "Model Evaluation": "모델 평가",
    "Moving Transform": "이동 변환",
    "Number of folds:": "폴드 수:",
    "Number of tokens": "토큰 수",
    "OWL file (*.owl)": "OWL 파일 (*.owl)",
    "Poisson Stirling": "Poisson Stirling",
    "Select Documents": "문서 선택",
    "Granger Causality": "Granger 인과관계",
    "Hide inner labels": "내부 레이블 숨기기",
    "No words overlap!": "겹치는 단어 없음!",
    "Number of skipped": "건너뛴 수",
    "Region attribute:": "지역 속성:",
    "Selected features": "선택된 특성",
    "Show cluster hull": "클러스터 외곽 표시",
    "Skipped documents": "건너뛴 문서",
    "Step/Play Through": "단계/재생",
    "Time series model": "시계열 모델",
    "Computing p-values": "p-값 계산 중",
    "Custom step size: ": "사용자 단계 크기: ",
    "Distance threshold": "거리 임계값",
    "Duplicates Cluster": "중복 클러스터",
    "Filter by word FDR": "단어 FDR 로 필터",
    "JSON file (*.json)": "JSON 파일 (*.json)",
    "Save Words to File": "단어를 파일에 저장",
    "Selected documents": "선택된 문서",
    "Sentiment Analysis": "감성 분석",
    "Show color regions": "색상 영역 표시",
    "Words displayed: 0": "표시된 단어: 0",
    "Duplicate Detection": "중복 감지",
    "Number of documents": "문서 수",
    "Open/Load Documents": "문서 열기/로드",
    "Seasonal Adjustment": "계절 조정",
    "Select a Time Range": "시간 범위 선택",
    "Computing FDR values": "FDR 값 계산 중",
    "Max p-value for word": "단어의 최대 p-값",
    "Word Scoring Methods": "단어 점수 방법",
    "Conllu import options": "Conllu 가져오기 옵션",
    "Evaluation Parameters": "평가 매개변수",
    "Save Ontology to File": "온톨로지를 파일에 저장",
    "Called from JavaScript": "JavaScript 에서 호출됨",
    "Filter by word p-value": "단어 p-값으로 필터",
    "Import Words from File": "파일에서 단어 가져오기",
    "Overall term frequency": "전체 용어 빈도",
    "Color points by cluster": "클러스터별 점 색상",
    "Create a list of words.": "단어 목록 생성.",
    "Error during processing": "처리 중 오류",
    "Gaussian mixture models": "가우시안 혼합 모델",
    "Select Top Level Folder": "최상위 폴더 선택",
    "Selected data is empty!": "선택된 데이터가 비어 있습니다!",
    "Display corpus contents.": "코퍼스 내용 표시.",
    "Import Ontology from URL": "URL 에서 온톨로지 가져오기",
    "No document set selected": "선택된 문서 집합 없음",
    "No valid embedding data.": "유효한 임베딩 데이터 없음.",
    "Corpus Without Duplicates": "중복 없는 코퍼스",
    "Import Ontology from File": "파일에서 온톨로지 가져오기",
    "No bag-of-words features!": "Bag-of-words 특성 없음!",
    "Sort words alphabetically": "단어를 알파벳 순으로 정렬",
    "Marginal Topic Probability": "한계 토픽 확률",
    "One or more models failed.": "하나 이상의 모델이 실패했습니다.",
    "Playback/Tracking interval": "재생/추적 간격",
    "Copy word list from library": "라이브러리에서 단어 목록 복사",
    "Reload current document set": "현재 문서 집합 다시 로드",
    "Term frequency within topic": "토픽 내 용어 빈도",
    "Compute sentiment from text.": "텍스트에서 감성 계산.",
    "Data has no useful variables": "데이터에 유용한 변수가 없습니다",
    "Mark segment as (un)selected": "세그먼트를 (비)선택으로 표시",
    "Not enough instances in data.": "데이터에 인스턴스가 부족합니다.",
    "Remove word list from library": "라이브러리에서 단어 목록 제거",
    "Selected features for Axis x ": "X축에 대한 선택된 특성 ",
    "Data contains no time variable": "데이터에 시간 변수가 없습니다",
    "Evaluate different time series": "다양한 시계열 평가",
    "Filter model for documents list": "문서 목록을 위한 필터 모델",
    "Timedelta larger than 100 years": "100년을 초과하는 timedelta",
    "Display the context of the word.": "단어의 문맥 표시.",
    "Load a corpus of text documents.": "텍스트 문서 코퍼스 로드.",
    "Add a new ontology to the library": "라이브러리에 새 온톨로지 추가",
    "All examples can not be selected!": "모든 예제를 선택할 수 없습니다!",
    "Create a new corpus and output it": "새 코퍼스를 생성하고 출력",
    "Data contains only one time point": "데이터에 시점이 하나뿐입니다",
    "Data has no continuous variables.": "데이터에 연속 변수가 없습니다.",
    "Add a new word list to the library": "라이브러리에 새 단어 목록 추가",
    "Duplicate detection only supports ": "중복 감지는 다음만 지원합니다 ",
    "Folder contains no readable files.": "폴더에 읽을 수 있는 파일이 없습니다.",
    "Pickled Python object file (*.pkl)": "피클된 Python 객체 파일 (*.pkl)",
    "Import text documents from folders.": "폴더에서 텍스트 문서 가져오기.",
    "More than one document is required.": "두 개 이상의 문서가 필요합니다.",
    "Set selected items in the list view": "리스트 뷰에서 선택 항목 설정",
    "Whether or not d is a whole number.": "d 가 정수인지 여부.",
    "Remove the ontology from the library": "라이브러리에서 온톨로지 제거",
    "Return the currently selected binning": "현재 선택된 구간 반환",
    "Save changes in the editor to library": "편집기의 변경 사항을 라이브러리에 저장",
    "Frequency of the word in the document.": "문서 내 단어 빈도.",
    "Interactive exploration of LDA topics.": "LDA 토픽의 대화형 탐색.",
    "Adding hash of documents to the context": "문서의 해시를 컨텍스트에 추가 중",
    "Input needs at least one Text variable.": "입력에 텍스트 변수가 최소 하나 필요합니다.",
    "Return the directory from a QDropEvent.": "QDropEvent 에서 디렉토리 반환.",
    "Delete word with delete or backspace key": "Delete 또는 Backspace 키로 단어 삭제",
    "Include selected words into the ontology": "선택된 단어를 온톨로지에 포함",
    "Remove word recursively (incl. children)": "재귀적으로 단어 제거 (하위 포함)",
    "Use Preprocess Text to normalize corpus.": "코퍼스 정규화에 '텍스트 전처리' 사용.",
    "Write/paste documents to create a corpus": "문서를 작성/붙여넣어 코퍼스 생성",
    "Compute significant bigrams and trigrams.": "유의미한 bigram 및 trigram 계산.",
    "Construct a text pre-processing pipeline.": "텍스트 전처리 파이프라인 구성.",
    "Detect & remove duplicates from a corpus.": "코퍼스에서 중복 감지 및 제거.",
    "Save changes in the editor to the library": "편집기의 변경 사항을 라이브러리에 저장",
    "Compute hash of all documents in the Corpus": "코퍼스 내 모든 문서의 해시 계산",
    "Delete element with delete or backspace key": "Delete 또는 Backspace 키로 요소 삭제",
    "List documents into the left scrolling area": "왼쪽 스크롤 영역에 문서 나열",
    "The task did not stop in in a timely manner": "작업이 적시에 중지되지 않았습니다",
    "Filter document that mathc the filter string": "필터 문자열과 일치하는 문서 필터링",
    "Relevant Terms only accepts output from LDA.": "'관련 용어' 는 LDA 의 출력만 허용합니다.",
    "Create new statistic variables for documents.": "문서에 대한 새 통계 변수 생성.",
    "Show the selected documents in the right area": "오른쪽 영역에 선택된 문서 표시",
    "Some words not embedded; try to rerun scoring": "일부 단어가 임베드되지 않음; 점수 다시 실행 시도",
    "TableView that disables unselecting all items": "전체 선택 해제를 비활성화하는 TableView",
    "Add editor on the click of Add document button": "'문서 추가' 버튼 클릭 시 편집기 추가",
    "Domain model that filter only visible features": "보이는 특성만 필터링하는 도메인 모델",
    "Context handler that matches hashes of documents": "문서 해시를 매칭하는 컨텍스트 핸들러",
    "Select a folder from which to load the documents": "문서를 로드할 폴더 선택",
    "Word enrichment analysis for selected documents.": "선택된 문서에 대한 단어 강화 분석.",
    "Remove tab and newline characters from the string": "문자열에서 탭과 개행 문자 제거",
    "Some documents not embedded; try to rerun scoring": "일부 문서가 임베드되지 않음; 점수 다시 실행 시도",
    "Apply rolling window functions to the time series.": "시계열에 롤링 윈도우 함수 적용.",
    "Infers characteristic words from the input corpus.": "입력 코퍼스에서 특성 단어 추론.",
    "Select a slice of measurements on a time interval.": "시간 구간에서 측정 슬라이스 선택.",
    "Uncover the hidden thematic structure in a corpus.": "코퍼스의 숨겨진 주제 구조 파악.",
    "Function is called every time the selection changes": "선택이 변경될 때마다 함수 호출",
    "Restore the original data order of the current view.": "현재 뷰의 원본 데이터 순서 복원.",
}
